### ISSUE TITLE
Allow bakers to stake/unstake

### ISSUE THREAD

**Issue by Zir0h** [trilitech/tezos-staking-app#61]
Hello

Currently the stake option is greyed out because bakers aren't actively delegating.
Would it be possible to add this option?
Screenshot is from my baker on tz1T1fRJmpPp1pN2z45sivxdbKNQtyatzCVx
![image](https://github.com/trilitech/tezos-staking-app/assets/546070/3226db7f-535c-40e7-8c6e-6e1feebaa2d2)

**Comment by ajinkyaraj-23** [comment]
Hi @Zir0h , we have released the next version. now bakers can also stake. Please give your feedback after trying it out.

**Comment by Zir0h** [comment]
> Hi @Zir0h , we have released the next version. now bakers can also stake. Please give your feedback after trying it out.

Working perfectly now, thank you for the addition!

Just a minor thing, but for bakers the lockup period is 2 cycles, not 4
![image](https://github.com/trilitech/tezos-staking-app/assets/546070/50a27c3a-da92-49b2-9e7f-48339ccee919)
